### ISSUE TITLE
DB Array value error

### ISSUE THREAD

**Issue by Julian559** [CSCI-150-LAB/Team4Repo#10]
I keep getting this error when entering trying to generate the listings for the forum posts. 

`<b>Notice</b>:  Trying to access array offset on value of type null in <b>C:\xampp\htdocs\150Project\pageForum.php</b> on line <b>199</b><br />`

The value is being put into the array and this is the same type of access being used for the donation listings.

**Comment by EnriqueVerduzco** [comment]
The error here is that the values in the array (User Posts/Data) is from a user that has since been deleted.
